DROP DATABASE IF EXISTS bookList;
CREATE DATABASE bookList;

USE bookList;

CREATE TABLE Books (
	bookID INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	author VARCHAR(50) NOT NULL,
	pages INT NOT NULL,
	category CHAR(2) NOT NULL
);