version: "3.7"

services:
    app:
        image: gentux/php:lumen-5.6-ci
        volumes:
            - ./:/var/www
        networks:
            - modules
    web:
        image: gentux/nginx:fpm
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
        links:
            - app:fpm.local
        networks:
            - modules
    mysql:
        image: mysql:5.6
        environment:
            MYSQL_DATABASE: "bookList"
            MYSQL_USER: "modules"
            MYSQL_PASSWORD: "secret"
            MYSQL_ROOT_PASSWORD: "secret"
        ports:
            - "3307:3306"
        networks:
            - modules
networks:
    modules: