version: "3.7"

services:
    hello-container:
        image: gentux/alpine-bash:ericabwalker
        volumes:  
            - ./scripts:/home/scripts
        command: /home/scripts/welcome-compose.sh

    data-container:
        image: alpine:latest 
        volumes: 
            - ./scripts:/home/scripts

    app:
        image: gentux/php:lumen-5.6-ci
        volumes:
            - ./:/var/www
        networks:
            - modules
            
    web:
        image: gentux/nginx:fpm
        ports:
            - "80:80"
        links:
            - app:fpm.local
        networks:
            - modules      
            
    mysql:
        image: mysql:5.6
        environment:
            MYSQL_DATABASE: "modules"
            MYSQL_USER: "modules"
            MYSQL_PASSWORD: "secret"
            MYSQL_ROOT_PASSWORD: "secret"
        ports:
            - "3306:3306"
        networks:
            - modules
                       
networks:
    modules:


        # services:
        #     client:
        #         image: nginx
        #         ports:
        #             - 8000:80
        #         volumes:
        #             - ./src:/usr/share/nginx/html